[package]
name = "spin-kube-app"
authors = ["Nuno do Carmo <nuno.carmo@suse.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "3.0.1"

[workspace]
