spin_manifest_version = 2

[application]
name = "spin-kube-app"
version = "0.1.0"
authors = ["Nuno do Carmo <nuno.carmo@suse.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin-kube-app"

[component.spin-kube-app]
source = "target/wasm32-wasi/release/spin_kube_app.wasm"
allowed_outbound_hosts = []
[component.spin-kube-app.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
